### ISSUE TITLE
 Make Some Offset - Too Sensitive on Mobile

### ISSUE THREAD

**Issue by marklchaves** [marklchaves/hide-and-seek-header#9]
Submitted by @kevinsu0201 on the [Avada Community Forum](https://theme-fusion.com/forums/topic/avada-sticky-header-on-scroll-up-only/) on 25 April 2020.

>Thanks a million for sharing the Hide and Seek Header plugin @marklchaves!!!
I am a self-studying newbee on wordpress and using the AVADA theme. You plugin works pretty great for my site.
I was wondering any chance to make some offset to the plugin? Because right now it seems little bit too sensitive, especially on mobile. When I slide the screen down (the content going up), with my hands touching the screen and causing tiny little up moving unintenionally, you will see the sticky header shows up quite frequently, which is a little bit odd. So I was thinking would it be better to add some offset to stop it from happening. Hope I discribe clearly the problem. And I really wish to get your attention on this. Thanks again!

**Comment by marklchaves** [comment]
Created dev [branch](https://github.com/marklchaves/hide-and-seek-header/tree/scroll-up-sensitivity).

Created initial sensitivity switch. In testing.

**Comment by marklchaves** [comment]
Completed the first iteration. Merged dev branch to master. Next: prepare release to WP.org.

**Comment by kevinsu0201** [comment]
Great job!

**Comment by marklchaves** [comment]
Thanks @kevinsu0201!

I have a few new projects going on this week. But, I should be able to get this released by the end of this week. Thanks for your support.

mark

**Comment by marklchaves** [comment]
Version 1.2.0 is available on [WordPress.org](https://wordpress.org/plugins/hide-and-seek-header/).

This version has a "beta" instance of the new scroll-up sensitivity setting. Please report issues here or on the [plugin forum](https://wordpress.org/support/plugin/hide-and-seek-header/).

Enjoy!

**Comment by marklchaves** [comment]
> Great job!

Hi @kevinsu0201,

This is released. Let me know how it goes :-)

mark

**Comment by kevinsu0201** [comment]
Hi @marklchaves,
Have tested the plugin, it is now working great on the phone. The header does not show up that frequently with unintentional operation. Thanks!

**Comment by kevinsu0201** [comment]
But at the same time I think I've come accross with another issue. I'm using a mega menu to my product menu. If mouse over my product menu, the product mega menu drops down, and if I move over the mega menu and scroll down, then you see the header and the mega menu hides. But actually I can still click those links on the mega menu, which means the mega menu may have not really hidden, it is just turnning the opacity to zero, that's you can still click the link on the mega menu even if they are invisible. Actually, it is not just the mega menu that causes this issue, but also other dropdown menu will, as long as you keep cursor on the dropdown menu when scrolling down (the header diasppears), the issue occurs. Finally, if you move the cursor away from the mega menu area, this issue disappear. Here is my site to help you understand the issue www.cosiagel.xyz
